---
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: localhost:24317 # By default only host system has access
  filelog:
    include: ["/var/log/*.log"]
    include_file_path: true
  hostmetrics:
    collection_interval: 1m
    scrapers:
      load:
      filesystem:
      memory:
      network:
      paging:
      process:
      system:

processors:
  batch: {}
  transform/severity_parse:
    log_statements:
      - context: log
        statements:
          - set(severity_text, "Info") where IsMatch(body.string, ".*INFO.*")
          - set(severity_text, "Warn") where IsMatch(body.string, ".*WARN.*")
          - set(severity_text, "Error") where IsMatch(body.string, ".*ERROR.*")
          - set(severity_text, "Fatal") where IsMatch(body.string, ".*FATAL.*")
  filter: {}
  tail_sampling: {}
  probabilistic_sampler: {}
  k8sattributes: {}
  memory_limiter: 
    check_interval: 1s
    limit_mib: 512

extensions:
  health_check:
    path: /health

exporters:
  # debug:                # Logs all received spans, metrics, and logs at the debug level.
  #   verbosity: detailed # Very useful for validating what the collector is receiving and sending.
  #                       # If enabled be sure to add debug to the exporters map for pipelines (traces, metrics, logs) 
  otlp:
    endpoint: ${env:INSTANA_OTEL_ENDPOINT_GRPC:-localhost:4317}
    headers:
      x-instana-key: ${env:INSTANA_KEY:-instanalocal}
      x-instana-host: ${env:HOSTNAME:-hostname}
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
    logs:
      receivers: [otlp, filelog]
      processors: [transform/severity_parse, batch]
      exporters: [otlp]
    metrics:
      receivers: [otlp, hostmetrics]
      processors: [batch]
      exporters: [otlp]
  extensions: [health_check]
  telemetry:
    logs:
#       level: debug  # Enables verbose logging for the collector's internal operations.
#                     # Useful when troubleshooting pipeline behavior or configuration issues.
      processors:
        - batch:
            exporter:
              otlp:
                protocol: http/protobuf
                endpoint: ${env:INSTANA_OTEL_ENDPOINT_HTTP:-http://localhost:8992}
                headers:
                  x-instana-key: ${env:INSTANA_KEY:-instanalocal}
    metrics:
      readers:
        - periodic:
            exporter:
              otlp:
                protocol: http/protobuf
                endpoint: ${env:INSTANA_OTEL_ENDPOINT_HTTP:-http://localhost:8992}
                headers:
                  x-instana-key: ${env:INSTANA_KEY:-instanalocal}
    resource:
      service.name: ${env:INSTANA_OTEL_SERVICE_NAME:-otel-collector}
      service.version: ${env:INSTANA_OTEL_SERVICE_VERSION:-1.0.299}
      service.instance.id: ${env:HOSTNAME:-hostname}
      entity.type: ${env:INSTANA_OTEL_ENTITY_TYPE:-otel-collector}
