---
dist:
  name: otelcol-dev
  description: Instana Distibution of OpenTelemetry Collector
  output_path: ./otelcol-dev
  # otelcol_version: 0.118.0
exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.118.0
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.118.0
processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.118.0
  - gomod: 
      github.com/open-telemetry/opentelemetry-collector-contrib/processor/transformprocessor 
      v0.119.0
receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.118.0
  - gomod:
      github.com/open-telemetry/opentelemetry-collector-contrib/receiver/filelogreceiver v0.118.0
# extensions:
#   - gomod:
#       github.com/open-telemetry/opentelemetry-collector-contrib/extension/opampextension
#       v0.118.0
providers:
  - gomod: go.opentelemetry.io/collector/confmap/provider/envprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/fileprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpsprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/yamlprovider v1.18.0
