---
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:24317
  filelog:
    include: ["/var/log/*.log"]
    include_file_path: true
  hostmetrics:
    collection_interval: 1m
    scrapers:
      load:
      filesystem:
      memory:
      network:
      paging:
      process:
      system:
processors:
  batch: {}
  transform/severity_parse:
    log_statements:
      - context: log
        statements:
          - set(severity_text, "Info") where IsMatch(body.string, ".*INFO.*")
          - set(severity_text, "Warn") where IsMatch(body.string, ".*WARN.*")
          - set(severity_text, "Error") where IsMatch(body.string, ".*ERROR.*")
          - set(severity_text, "Fatal") where IsMatch(body.string, ".*FATAL.*")
exporters:
  debug:
    verbosity: detailed
  otlp:
    endpoint: ${env:INSTANA_OTEL_ENDPOINT_GRPC:-localhost:4317}
    headers:
      x-instana-key: ${env:INSTANA_KEY:-instanalocal}
      x-instana-host: ${env:INSTANA_HOST:-"yourhost.ibm.com"}
    tls:
      insecure: true
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp, debug]
    logs:
      receivers: [otlp, filelog]
      processors: [transform/severity_parse, batch]
      exporters: [otlp]
    metrics:
      receivers: [otlp, hostmetrics]
      processors: [batch]
      exporters: [otlp, debug]
  telemetry:
    logs:
      level: debug
      processors:
        - batch:
            exporter:
              otlp:
                protocol: http/protobuf
                endpoint: ${env:INSTANA_OTEL_ENDPOINT_HTTP:-http://localhost:8992}
                headers:
                  x-instana-key: ${env:INSTANA_KEY:-instanalocal}
    metrics:
      readers:
        - periodic:
            exporter:
              otlp:
                protocol: grpc/protobuf
                endpoint: ${env:INSTANA_OTEL_ENDPOINT_GRPC:-localhost:4317}
                headers:
                  x-instana-key: ${env:INSTANA_KEY:-instanalocal}
#   extensions: [opamp]
# extensions:
#   opamp:
#     server:
#       ws:
#         endpoint: ws://127.0.0.1:4320/v1/opamp
#         tls:
#           insecure_skip_verify: true
