---
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:24317
  filelog:
    include: ["/var/log/*.log"]
    include_file_path: true
processors:
  batch: {}
  transform/severity_parse:
    log_statements:
      - context: log
        statements:
          - set(severity_text, "Info") where IsMatch(body.string, ".*INFO.*")
          - set(severity_text, "Warn") where IsMatch(body.string, ".*WARN.*")
          - set(severity_text, "Error") where IsMatch(body.string, ".*ERROR.*")
          - set(severity_text, "Fatal") where IsMatch(body.string, ".*FATAL.*")
exporters:
  debug:
    verbosity: detailed
  otlp:
    endpoint: localhost:4317
    headers:
      x-instana-key: instanalocal
      x-instana-host: "yourhost.ibm.com"
    tls:
      insecure: true
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp, debug]
    logs:
      receivers: [otlp, filelog]
      processors: [transform/severity_parse, batch]
      exporters: [otlp, debug]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp, debug]
  telemetry:
    logs:
      level: debug
#   extensions: [opamp]
# extensions:
#   opamp:
#     server:
#       ws:
#         endpoint: ws://127.0.0.1:4320/v1/opamp
#         tls:
#           insecure_skip_verify: true
