// Code generated by mdatagen. DO NOT EDIT.

package metadatatest

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"
	"go.opentelemetry.io/otel/sdk/metric/metricdata"
	"go.opentelemetry.io/otel/sdk/metric/metricdata/metricdatatest"

	"github.com/open-telemetry/opentelemetry-collector-contrib/processor/spanintentprocessor/internal/metadata"
	"go.opentelemetry.io/collector/component/componenttest"
)

func TestSetupTelemetry(t *testing.T) {
	testTel := componenttest.NewTelemetry()
	tb, err := metadata.NewTelemetryBuilder(testTel.NewTelemetrySettings())
	require.NoError(t, err)
	defer tb.Shutdown()
	tb.ProcessorSpanintentErrorsTotal.Add(context.Background(), 1)
	tb.ProcessorSpanintentNewTraceIDReceived.Add(context.Background(), 1)
	tb.ProcessorSpanintentSampledCacheHits.Add(context.Background(), 1)
	tb.ProcessorSpanintentSampledCacheMisses.Add(context.Background(), 1)
	tb.ProcessorSpanintentSamplingDecisionLatency.Record(context.Background(), 1)
	tb.ProcessorSpanintentSpansReceived.Add(context.Background(), 1)
	tb.ProcessorSpanintentSpansSampled.Add(context.Background(), 1)
	tb.ProcessorSpanintentSpansUnsampled.Add(context.Background(), 1)
	tb.ProcessorSpanintentTraceBufferSize.Record(context.Background(), 1)
	tb.ProcessorSpanintentTracesClassifiedTotal.Add(context.Background(), 1)
	tb.ProcessorSpanintentTracesSampled.Add(context.Background(), 1)
	tb.ProcessorSpanintentTracesUnsampled.Add(context.Background(), 1)
	tb.ProcessorSpanintentUnsampledCacheHits.Add(context.Background(), 1)
	tb.ProcessorSpanintentUnsampledCacheMisses.Add(context.Background(), 1)
	AssertEqualProcessorSpanintentErrorsTotal(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualProcessorSpanintentNewTraceIDReceived(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualProcessorSpanintentSampledCacheHits(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualProcessorSpanintentSampledCacheMisses(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualProcessorSpanintentSamplingDecisionLatency(t, testTel,
		[]metricdata.HistogramDataPoint[float64]{{}}, metricdatatest.IgnoreValue(),
		metricdatatest.IgnoreTimestamp())
	AssertEqualProcessorSpanintentSpansReceived(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualProcessorSpanintentSpansSampled(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualProcessorSpanintentSpansUnsampled(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualProcessorSpanintentTraceBufferSize(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualProcessorSpanintentTracesClassifiedTotal(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualProcessorSpanintentTracesSampled(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualProcessorSpanintentTracesUnsampled(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualProcessorSpanintentUnsampledCacheHits(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualProcessorSpanintentUnsampledCacheMisses(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())

	require.NoError(t, testTel.Shutdown(context.Background()))
}
