// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"errors"
	"sync"

	"go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/trace"

	"go.opentelemetry.io/collector/component"
)

func Meter(settings component.TelemetrySettings) metric.Meter {
	return settings.MeterProvider.Meter("github.com/open-telemetry/opentelemetry-collector-contrib/processor/spanintentprocessor")
}

func Tracer(settings component.TelemetrySettings) trace.Tracer {
	return settings.TracerProvider.Tracer("github.com/open-telemetry/opentelemetry-collector-contrib/processor/spanintentprocessor")
}

// TelemetryBuilder provides an interface for components to report telemetry
// as defined in metadata and user config.
type TelemetryBuilder struct {
	meter                                      metric.Meter
	mu                                         sync.Mutex
	registrations                              []metric.Registration
	ProcessorSpanintentErrorsTotal             metric.Int64Counter
	ProcessorSpanintentNewTraceIDReceived      metric.Int64Counter
	ProcessorSpanintentProcessingDuration      metric.Float64Histogram
	ProcessorSpanintentSampledCacheHits        metric.Int64Counter
	ProcessorSpanintentSampledCacheMisses      metric.Int64Counter
	ProcessorSpanintentSamplingDecisionLatency metric.Float64Histogram
	ProcessorSpanintentSpansReceived           metric.Int64Counter
	ProcessorSpanintentTraceBufferSize         metric.Int64Gauge
	ProcessorSpanintentTracesClassifiedTotal   metric.Int64Counter
	ProcessorSpanintentTracesProcessed         metric.Int64Counter
	ProcessorSpanintentTracesSampled           metric.Int64Counter
	ProcessorSpanintentTracesUnsampled         metric.Int64Counter
	ProcessorSpanintentUnsampledCacheHits      metric.Int64Counter
	ProcessorSpanintentUnsampledCacheMisses    metric.Int64Counter
}

// TelemetryBuilderOption applies changes to default builder.
type TelemetryBuilderOption interface {
	apply(*TelemetryBuilder)
}

type telemetryBuilderOptionFunc func(mb *TelemetryBuilder)

func (tbof telemetryBuilderOptionFunc) apply(mb *TelemetryBuilder) {
	tbof(mb)
}

// Shutdown unregister all registered callbacks for async instruments.
func (builder *TelemetryBuilder) Shutdown() {
	builder.mu.Lock()
	defer builder.mu.Unlock()
	for _, reg := range builder.registrations {
		reg.Unregister()
	}
}

// NewTelemetryBuilder provides a struct with methods to update all internal telemetry
// for a component
func NewTelemetryBuilder(settings component.TelemetrySettings, options ...TelemetryBuilderOption) (*TelemetryBuilder, error) {
	builder := TelemetryBuilder{}
	for _, op := range options {
		op.apply(&builder)
	}
	builder.meter = Meter(settings)
	var err, errs error
	builder.ProcessorSpanintentErrorsTotal, err = builder.meter.Int64Counter(
		"otelcol_processor_spanintent_errors_total",
		metric.WithDescription("Total number of errors encountered during span intent processing."),
		metric.WithUnit("{errors}"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorSpanintentNewTraceIDReceived, err = builder.meter.Int64Counter(
		"otelcol_processor_spanintent_new_trace_id_received",
		metric.WithDescription("Number of new unique trace IDs received by the span intent processor."),
		metric.WithUnit("{traces}"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorSpanintentProcessingDuration, err = builder.meter.Float64Histogram(
		"otelcol_processor_spanintent_processing_duration",
		metric.WithDescription("Duration of the span intent processor's main processing loop (processBufferedSpans)."),
		metric.WithUnit("ms"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorSpanintentSampledCacheHits, err = builder.meter.Int64Counter(
		"otelcol_processor_spanintent_sampled_cache_hits",
		metric.WithDescription("Number of hits in the sampled traces cache."),
		metric.WithUnit("{spans}"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorSpanintentSampledCacheMisses, err = builder.meter.Int64Counter(
		"otelcol_processor_spanintent_sampled_cache_misses",
		metric.WithDescription("Number of misses in the sampled traces cache."),
		metric.WithUnit("{spans}"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorSpanintentSamplingDecisionLatency, err = builder.meter.Float64Histogram(
		"otelcol_processor_spanintent_sampling_decision_latency",
		metric.WithDescription("Latency of making a sampling decision for a single trace"),
		metric.WithUnit("us"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorSpanintentSpansReceived, err = builder.meter.Int64Counter(
		"otelcol_processor_spanintent_spans_received",
		metric.WithDescription("Number of spans received by the span intent processor."),
		metric.WithUnit("{spans}"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorSpanintentTraceBufferSize, err = builder.meter.Int64Gauge(
		"otelcol_processor_spanintent_trace_buffer_size",
		metric.WithDescription("Current number of unique trace IDs in the internal buffer."),
		metric.WithUnit("{spans}"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorSpanintentTracesClassifiedTotal, err = builder.meter.Int64Counter(
		"otelcol_processor_spanintent_traces_classified_total",
		metric.WithDescription("Total number of traces classified by intent."),
		metric.WithUnit("{traces}"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorSpanintentTracesProcessed, err = builder.meter.Int64Counter(
		"otelcol_processor_spanintent_traces_processed",
		metric.WithDescription("Number of traces processed by the span intent processor."),
		metric.WithUnit("{traces}"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorSpanintentTracesSampled, err = builder.meter.Int64Counter(
		"otelcol_processor_spanintent_traces_sampled",
		metric.WithDescription("Number of traces sampled by the span intent processor."),
		metric.WithUnit("{traces}"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorSpanintentTracesUnsampled, err = builder.meter.Int64Counter(
		"otelcol_processor_spanintent_traces_unsampled",
		metric.WithDescription("Number of traces unsampled by the span intent processor."),
		metric.WithUnit("{traces}"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorSpanintentUnsampledCacheHits, err = builder.meter.Int64Counter(
		"otelcol_processor_spanintent_unsampled_cache_hits",
		metric.WithDescription("Number of hits in the unsampled traces cache."),
		metric.WithUnit("{spans}"),
	)
	errs = errors.Join(errs, err)
	builder.ProcessorSpanintentUnsampledCacheMisses, err = builder.meter.Int64Counter(
		"otelcol_processor_spanintent_unsampled_cache_misses",
		metric.WithDescription("Number of misses in the unsampled traces cache."),
		metric.WithUnit("{spans}"),
	)
	errs = errors.Join(errs, err)
	return &builder, errs
}
