{{/* OpenShift DaemonSet Service Account with Privileged SCC */}}
{{- $usePrivilegedSA := true -}}
{{- if hasKey .Values "openshift" -}}
  {{- if hasKey .Values.openshift "daemonset" -}}
    {{- if hasKey .Values.openshift.daemonset "usePrivilegedServiceAccount" -}}
      {{- $usePrivilegedSA = .Values.openshift.daemonset.usePrivilegedServiceAccount -}}
    {{- end -}}
  {{- end -}}
{{- end -}}
{{- if and (eq (include "instana-otel-collector.isOpenShift" .) "true") $usePrivilegedSA -}}
{{- $sccName := printf "%s-scc" .Release.Name -}}
{{- $saName := printf "%s-daemonset" .Release.Name -}}
{{- if not (lookup "v1" "ServiceAccount" .Release.Namespace $saName) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $saName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: agent-collector
    app.kubernetes.io/name: daemonset
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end -}}
---
{{- if (.Capabilities.APIVersions.Has "security.openshift.io/v1") }}
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: {{ $sccName }}
  annotations:
    kubernetes.io/description: "Privileged SCC for Instana OpenTelemetry Collector DaemonSet"
allowHostDirVolumePlugin: true
allowHostIPC: false
allowHostNetwork: true
allowHostPID: true
allowHostPorts: true
allowPrivilegeEscalation: true
allowPrivilegedContainer: true
allowedCapabilities:
- '*'
defaultAddCapabilities: null
fsGroup:
  type: RunAsAny
groups:
- system:cluster-admins
priority: 10
readOnlyRootFilesystem: false
requiredDropCapabilities: null
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
seccompProfiles:
- '*'
supplementalGroups:
  type: RunAsAny
users:
- system:serviceaccount:{{ .Release.Namespace }}:{{ $saName }}
volumes:
- '*'
{{- end }}
{{- end }}
